version: '3'

services:
  fastock-chain-daemon-node0:
    container_name: fastock-chain-daemon-node0
    image: "fastock-chain/node"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-fastock-chain-daemon.log}
    volumes:
      - ./build:/fastock-chain-daemon:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  fastock-chain-daemon-node1:
    container_name: fastock-chain-daemon-node1
    image: "fastock-chain/node"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-fastock-chain-daemon.log}
    volumes:
      - ./build:/fastock-chain-daemon:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  fastock-chain-daemon-node2:
    container_name: fastock-chain-daemon-node2
    image: "fastock-chain/node"
    environment:
      - ID=2
      - LOG=${LOG:-fastock-chain-daemon.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/fastock-chain-daemon:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  fastock-chain-daemon-node3:
    container_name: fastock-chain-daemon-node3
    image: "fastock-chain/node"
    environment:
      - ID=3
      - LOG=${LOG:-fastock-chain-daemon.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/fastock-chain-daemon:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

